use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(serde::Deserialize)]
struct Manifest {
    assets: Vec<AssetEntry>,
    icons: IconEntries,
}

#[derive(serde::Deserialize)]
struct AssetEntry {
    url: String,
    content_type: String,
    etag: String,
    gz: String,
    br: String,
}

#[derive(serde::Deserialize)]
struct IconEntries {
    svg: String,
    png_192: String,
    png_512: String,
}

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dist_dir = PathBuf::from(&crate_dir).parent().unwrap().join("dist");
    let manifest_path = dist_dir.join("manifest.json");

    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let generated = if manifest_path.exists() {
        let raw = fs::read_to_string(&manifest_path)
            .unwrap_or_else(|e| panic!("read {}: {}", manifest_path.display(), e));
        let manifest: Manifest = serde_json::from_str(&raw)
            .unwrap_or_else(|e| panic!("parse {}: {}", manifest_path.display(), e));
        for asset in &manifest.assets {
            println!("cargo:rerun-if-changed={}", dist_dir.join(&asset.gz).display());
            println!("cargo:rerun-if-changed={}", dist_dir.join(&asset.br).display());
        }
        println!(
            "cargo:rerun-if-changed={}",
            dist_dir.join(&manifest.icons.svg).display()
        );
        println!(
            "cargo:rerun-if-changed={}",
            dist_dir.join(&manifest.icons.png_192).display()
        );
        println!(
            "cargo:rerun-if-changed={}",
            dist_dir.join(&manifest.icons.png_512).display()
        );
        emit_real(&dist_dir, &manifest)
    } else {
        emit_placeholder()
    };

    let dest = Path::new(&out_dir).join("client_assets_generated.rs");
    fs::write(&dest, generated).expect("write client_assets_generated.rs");
}

fn emit_real(dist: &Path, m: &Manifest) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — do not edit.\n\n");

    out.push_str(&format!(
        "pub static ICON_SVG: &[u8] = include_bytes!(r\"{}\");\n",
        dist.join(&m.icons.svg).display()
    ));
    out.push_str(&format!(
        "pub static ICON_PNG_192: &[u8] = include_bytes!(r\"{}\");\n",
        dist.join(&m.icons.png_192).display()
    ));
    out.push_str(&format!(
        "pub static ICON_PNG_512: &[u8] = include_bytes!(r\"{}\");\n\n",
        dist.join(&m.icons.png_512).display()
    ));

    out.push_str("pub struct EmbeddedAsset {\n");
    out.push_str("    pub url: &'static str,\n");
    out.push_str("    pub content_type: &'static str,\n");
    out.push_str("    pub etag: &'static str,\n");
    out.push_str("    pub gz: &'static [u8],\n");
    out.push_str("    pub br: &'static [u8],\n");
    out.push_str("}\n\n");

    out.push_str(&format!(
        "pub static CLIENT_ASSETS: &[EmbeddedAsset] = &[\n"
    ));
    for a in &m.assets {
        out.push_str("    EmbeddedAsset {\n");
        out.push_str(&format!("        url: {:?},\n", a.url));
        out.push_str(&format!("        content_type: {:?},\n", a.content_type));
        out.push_str(&format!("        etag: {:?},\n", a.etag));
        out.push_str(&format!(
            "        gz: include_bytes!(r\"{}\"),\n",
            dist.join(&a.gz).display()
        ));
        out.push_str(&format!(
            "        br: include_bytes!(r\"{}\"),\n",
            dist.join(&a.br).display()
        ));
        out.push_str("    },\n");
    }
    out.push_str("];\n");
    out
}

fn emit_placeholder() -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED placeholder (no dist/manifest.json found).\n\n");
    out.push_str("pub static ICON_SVG: &[u8] = b\"\";\n");
    out.push_str("pub static ICON_PNG_192: &[u8] = b\"\";\n");
    out.push_str("pub static ICON_PNG_512: &[u8] = b\"\";\n\n");
    out.push_str("pub struct EmbeddedAsset {\n");
    out.push_str("    pub url: &'static str,\n");
    out.push_str("    pub content_type: &'static str,\n");
    out.push_str("    pub etag: &'static str,\n");
    out.push_str("    pub gz: &'static [u8],\n");
    out.push_str("    pub br: &'static [u8],\n");
    out.push_str("}\n\n");
    out.push_str("pub static CLIENT_ASSETS: &[EmbeddedAsset] = &[];\n");
    out
}
