#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const args = new Set(Bun.argv.slice(2));
const noCompile = args.has("--no-compile");

console.log("[build] rasterizing icon ...");
const iconSvgPath = resolve(root, "src/icon.svg");
const iconSvg = await readFile(iconSvgPath, "utf8");
async function rasterize(size: number): Promise<Buffer> {
  const tmp = resolve(root, `src/generated/icon-${size}.png`);
  const proc = Bun.spawn({
    cmd: ["rsvg-convert", "-w", String(size), "-h", String(size), iconSvgPath, "-o", tmp],
    stderr: "pipe",
  });
  const code = await proc.exited;
  if (code !== 0) {
    const err = new TextDecoder().decode(await new Response(proc.stderr).arrayBuffer());
    throw new Error(`rsvg-convert exited ${code}: ${err}`);
  }
  return Buffer.from(await readFile(tmp));
}
const png192 = await rasterize(192);
const png512 = await rasterize(512);
console.log(`[build] icon-192.png: ${(png192.length / 1024).toFixed(1)} KB`);
console.log(`[build] icon-512.png: ${(png512.length / 1024).toFixed(1)} KB`);
const iconsModule = `// AUTO-GENERATED by scripts/build.ts — do not edit.
export const ICON_SVG_RAW = ${JSON.stringify(iconSvg)};
export const ICON_PNG_192_B64 = ${JSON.stringify(png192.toString("base64"))};
export const ICON_PNG_512_B64 = ${JSON.stringify(png512.toString("base64"))};
`;
await writeFile(resolve(root, "src/generated/icons.ts"), iconsModule);

console.log("[build] bundling client ...");
const clientResult = await Bun.build({
  entrypoints: [resolve(root, "src/client/main.ts")],
  target: "browser",
  format: "esm",
  minify: true,
  sourcemap: "none",
});
if (!clientResult.success) {
  for (const log of clientResult.logs) console.error(log);
  throw new Error("client bundle failed");
}
const clientArtifact = clientResult.outputs[0];
if (!clientArtifact) throw new Error("client bundle produced no output");
const clientJs = await clientArtifact.text();
const html = await readFile(resolve(root, "src/client/index.html"), "utf8");
const css = await readFile(resolve(root, "src/client/styles.css"), "utf8");

console.log(`[build] client.js: ${(clientJs.length / 1024).toFixed(1)} KB`);
console.log(`[build] styles.css: ${(css.length / 1024).toFixed(1)} KB`);
console.log(`[build] index.html: ${(html.length / 1024).toFixed(1)} KB`);

const generated = `// AUTO-GENERATED by scripts/build.ts — do not edit.
export const CLIENT_HTML = ${JSON.stringify(html)};
export const CLIENT_CSS = ${JSON.stringify(css)};
export const CLIENT_JS = ${JSON.stringify(clientJs)};
`;

const generatedPath = resolve(root, "src/generated/client-bundle.ts");
await mkdir(dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, generated);
console.log(`[build] wrote ${generatedPath}`);

if (noCompile) {
  console.log("[build] --no-compile, skipping binary");
  process.exit(0);
}

console.log("[build] compiling binary ...");
const compile = Bun.spawn({
  cmd: [
    "bun",
    "build",
    resolve(root, "src/server.ts"),
    "--compile",
    "--minify",
    "--outfile",
    resolve(root, "treepeek"),
  ],
  stdout: "inherit",
  stderr: "inherit",
});
const code = await compile.exited;
if (code !== 0) {
  console.error("[build] compile failed");
  process.exit(code);
}
console.log("[build] done → ./treepeek");
