#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const args = new Set(Bun.argv.slice(2));
const noCompile = args.has("--no-compile");

console.log("[build] bundling client ...");
const clientResult = await Bun.build({
  entrypoints: [resolve(root, "src/client/main.ts")],
  target: "browser",
  format: "esm",
  minify: true,
  sourcemap: "none",
});
if (!clientResult.success) {
  for (const log of clientResult.logs) console.error(log);
  throw new Error("client bundle failed");
}
const clientArtifact = clientResult.outputs[0];
if (!clientArtifact) throw new Error("client bundle produced no output");
const clientJs = await clientArtifact.text();
const html = await readFile(resolve(root, "src/client/index.html"), "utf8");
const css = await readFile(resolve(root, "src/client/styles.css"), "utf8");

console.log(`[build] client.js: ${(clientJs.length / 1024).toFixed(1)} KB`);
console.log(`[build] styles.css: ${(css.length / 1024).toFixed(1)} KB`);
console.log(`[build] index.html: ${(html.length / 1024).toFixed(1)} KB`);

const generated = `// AUTO-GENERATED by scripts/build.ts — do not edit.
export const CLIENT_HTML = ${JSON.stringify(html)};
export const CLIENT_CSS = ${JSON.stringify(css)};
export const CLIENT_JS = ${JSON.stringify(clientJs)};
`;

const generatedPath = resolve(root, "src/generated/client-bundle.ts");
await mkdir(dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, generated);
console.log(`[build] wrote ${generatedPath}`);

if (noCompile) {
  console.log("[build] --no-compile, skipping binary");
  process.exit(0);
}

console.log("[build] compiling binary ...");
const compile = Bun.spawn({
  cmd: [
    "bun",
    "build",
    resolve(root, "src/server.ts"),
    "--compile",
    "--minify",
    "--outfile",
    resolve(root, "treepeek"),
  ],
  stdout: "inherit",
  stderr: "inherit",
});
const code = await compile.exited;
if (code !== 0) {
  console.error("[build] compile failed");
  process.exit(code);
}
console.log("[build] done → ./treepeek");
